[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags = -DBOARD_HAS_PSRAM
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.36.18
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
lib_ignore = oled-ui-astra
